#!/usr/bin/env python3
"""The GlucoWatch icon in GlucoseDAO style: its ball-and-stick glucose molecule on a white disc.

One geometry, two outputs, so they cannot drift apart:

    app/src/main/res/drawable/ic_launcher.xml         vector for the launcher, tiles, complications
    phone/src/main/res/drawable/ic_launcher.xml       the companion app's matching icon
    fastlane/metadata/android/en-US/images/icon.png   512 px store icon

As in the GlucoseDAO logo: black carbons with grey centres, red oxygens, white hydrogens, black
bonds. The pyranose ring is drawn as a flat hexagon so it reads at launcher size.

    uv run scripts/make_icon.py        # Pillow comes from the repo pyproject.toml
"""
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VIEW = 48.0

BLACK, GREY, RED, WHITE = '#FF111111', '#FF9A9A9A', '#FFE0141E', '#FFFFFFFF'
BOND = 1.5
CARBON, CARBON_CORE = 3.3, 1.45
OXYGEN, HYDROGEN = 2.7, 1.55
OUTLINE = 0.8


def geometry():
    """Atoms as (x, y, kind) and bonds as index pairs, in the 48-unit viewport."""
    cx, cy, r = 24.0, 25.5, 8.2
    angles = [-30, 30, 90, 150, 210, 270]           # ring positions, degrees; 0 = right, y grows down
    ring = [(cx + r * math.cos(math.radians(a)), cy + r * math.sin(math.radians(a))) for a in angles]
    atoms, bonds = [], []
    # Ring: oxygen at the upper right (-30 deg), as in the logo, carbons elsewhere.
    for i, (x, y) in enumerate(ring):
        atoms.append((x, y, 'O' if i == 0 else 'C'))
    bonds += [(i, (i + 1) % 6) for i in range(6)]

    def outward(i, length):
        a = math.radians(angles[i])
        return ring[i][0] + length * math.cos(a), ring[i][1] + length * math.sin(a)

    def add(x, y, kind, to):
        atoms.append((x, y, kind))
        bonds.append((to, len(atoms) - 1))
        return len(atoms) - 1

    # Hydroxyl groups on four ring carbons, each O with its H a little further out and turned.
    for i, turn in ((1, 35), (2, -35), (3, 35), (4, -35)):
        ox, oy = outward(i, 6.6)
        o = add(ox, oy, 'O', i)
        a = math.radians(angles[i] + turn)
        add(ox + 4.4 * math.cos(a), oy + 4.4 * math.sin(a), 'H', o)
    # C6 above the top ring carbon, leaning right, with its hydroxyl pointing up and right.
    c6x, c6y = outward(5, 6.6)
    c6 = add(c6x + 3.2, c6y - 0.4, 'C', 5)
    o6 = add(atoms[c6][0] + 6.0, atoms[c6][1] - 2.4, 'O', c6)
    add(atoms[o6][0] + 4.0, atoms[o6][1] + 2.0, 'H', o6)
    # Centre the molecule, radii included, on the disc.
    radius = {'C': CARBON, 'O': OXYGEN + OUTLINE, 'H': HYDROGEN + OUTLINE}
    x0 = min(x - radius[k] for x, _, k in atoms); x1 = max(x + radius[k] for x, _, k in atoms)
    y0 = min(y - radius[k] for _, y, k in atoms); y1 = max(y + radius[k] for _, y, k in atoms)
    dx, dy = 24 - (x0 + x1) / 2, 24 - (y0 + y1) / 2
    atoms = [(x + dx, y + dy, k) for x, y, k in atoms]
    # Then shrink it (atoms, bonds and all) until every atom sits inside the disc with a margin.
    reach = max(math.hypot(x - 24, y - 24) + radius[k] for x, y, k in atoms)
    return atoms, bonds, min(1.0, 20.5 / reach)


def circle_path(x, y, r):
    return f'M{x - r:.2f},{y:.2f}a{r:.2f},{r:.2f} 0,1 0,{2 * r:.2f},0a{r:.2f},{r:.2f} 0,1 0,{-2 * r:.2f},0Z'


def vector(atoms, bonds, scale):
    parts = [circle_path(24, 24, 23)]
    out = ['<?xml version="1.0" encoding="utf-8"?>',
           '<!-- Generated by scripts/make_icon.py: the GlucoseDAO glucose molecule on a white disc. -->',
           '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
           '    android:width="48dp"', '    android:height="48dp"',
           '    android:viewportWidth="48"', '    android:viewportHeight="48">',
           f'    <path android:fillColor="{WHITE}" android:pathData="{parts[0]}" />']
    out.append(f'    <group android:pivotX="24" android:pivotY="24" android:scaleX="{scale:.3f}" android:scaleY="{scale:.3f}">')
    bond_path = ''.join(f'M{atoms[a][0]:.2f},{atoms[a][1]:.2f}L{atoms[b][0]:.2f},{atoms[b][1]:.2f}' for a, b in bonds)
    out.append(f'    <path android:strokeColor="{BLACK}" android:strokeWidth="{BOND}" android:strokeLineCap="round" android:pathData="{bond_path}" />')
    for x, y, kind in atoms:
        if kind == 'C':
            out.append(f'    <path android:fillColor="{BLACK}" android:pathData="{circle_path(x, y, CARBON)}" />')
            out.append(f'    <path android:fillColor="{GREY}" android:pathData="{circle_path(x, y, CARBON_CORE)}" />')
        else:
            fill, r = (RED, OXYGEN) if kind == 'O' else (WHITE, HYDROGEN)
            out.append(f'    <path android:fillColor="{fill}" android:strokeColor="{BLACK}" android:strokeWidth="{OUTLINE}" '
                       f'android:pathData="{circle_path(x, y, r)}" />')
    out.append('    </group>')
    out.append('</vector>')
    return '\n'.join(out) + '\n'


def png(atoms, bonds, scale, size=512, ss=4):
    from PIL import Image, ImageDraw
    n = size * ss
    k = n / VIEW
    rgb = lambda c: tuple(int(c[i:i + 2], 16) for i in (3, 5, 7))
    img = Image.new('RGBA', (n, n), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    d.ellipse((1 * k, 1 * k, 47 * k, 47 * k), fill=rgb(WHITE))
    # The same scaling as the vector's group: around the centre, sizes included.
    px = lambda v: (24 + (v - 24) * scale) * k
    size_px = lambda v: v * scale * k
    for a, b in bonds:
        d.line((px(atoms[a][0]), px(atoms[a][1]), px(atoms[b][0]), px(atoms[b][1])), fill=rgb(BLACK), width=round(size_px(BOND)))
    for x, y, kind in atoms:
        box = lambda r: (px(x) - size_px(r), px(y) - size_px(r), px(x) + size_px(r), px(y) + size_px(r))
        if kind == 'C':
            d.ellipse(box(CARBON), fill=rgb(BLACK))
            d.ellipse(box(CARBON_CORE), fill=rgb(GREY))
        else:
            fill, r = (RED, OXYGEN) if kind == 'O' else (WHITE, HYDROGEN)
            d.ellipse(box(r + OUTLINE / 2), fill=rgb(BLACK))
            d.ellipse(box(r - OUTLINE / 2), fill=rgb(fill))
    return img.resize((size, size), Image.LANCZOS)


def main():
    atoms, bonds, scale = geometry()
    for module in ('app', 'phone'):
        (ROOT / module / 'src/main/res/drawable/ic_launcher.xml').write_text(vector(atoms, bonds, scale))
    png(atoms, bonds, scale).save(ROOT / 'fastlane/metadata/android/en-US/images/icon.png', optimize=True)
    print('wrote app and phone ic_launcher.xml and icon.png')


if __name__ == '__main__':
    main()
